sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - "pip install pytest-cov coveralls cython"
compiler:
  - gcc
  - clang
# command to install dependencies
install:
  - "python setup.py build_ext --inplace"
# command to run tests
script: py.test --cov=daedalus daedalus
after_success: coveralls
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
