sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - "pip install pytest-cov coveralls cython"
compiler:
  - gcc
  - clang
# command to install dependencies
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - "python setup.py build_ext --inplace"
# command to run tests
script: py.test --cov=daedalus daedalus
after_success: coveralls
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
